stages:
  - build
  - deploy

build:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:9.0
  script:
    - dotnet restore
    - dotnet build Panda.NuGet.BillbeeClient

deploy:
  image: mcr.microsoft.com/dotnet/sdk:9.0
  stage: deploy
  before_script:
    - dotnet nuget add source "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/nuget/index.json" --name gitlabci --username gitlab-ci-token --password $CI_JOB_TOKEN --store-password-in-clear-text
  script:
    - dotnet pack -c Release -o Packages -p:PackageVersion=$CI_COMMIT_TAG Panda.NuGet.BillbeeClient
    - dotnet nuget push "Packages/*.nupkg" --source gitlabci
  only:
    - tags